name: 1GP CI build
on:
  pull_request:
    branches:
      - release

  merge_group:
    types: [checks_requested]

  workflow_dispatch:
    inputs:
      clean-org:
        description: |
          ( true | false ) Whether to use a clean org or an org from OrgFarm.
          Defaults to using an OrgFarm org.
        required: false
        type: boolean
        default: false

      preserve-org:
        description: |
          ( true | false ) Whether to preserve the org after the workflow completes.
          Auth information is stored in the build artifacts.
        required: false
        type: boolean
        default: false

permissions:
  contents: read # This is required for actions/checkout

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: ${{ github.ref != 'refs/heads/release' }}

jobs:
  Get-Package-Info:
    runs-on: ubuntu-latest
    outputs:
      package-name: ${{ steps.get-package-info.outputs.package-name }}
      package-namespace: ${{ steps.get-package-info.outputs.package-namespace }}
      subscriber-package-id: ${{ steps.get-package-info.outputs.subscriber-package-id }}
      sfdx-project-json: ${{ steps.get-package-info.outputs.sfdx-project-json }}
    steps:
      - name: 🗃️ Checkout Repo 🗃️
        uses: actions/checkout@v5

      - name: Get Package Info
        id: get-package-info
        uses: ./.github/actions/getPackageInfo

  Path-Filtering:
    needs: Get-Package-Info
    runs-on: ubuntu-latest
    outputs:
      build-required: ${{ steps.path-filter.outputs.build-required }}
    steps:
      - name: 🗃️ Checkout Repo 🗃️
        uses: actions/checkout@v5

      - name: Path Filtering
        id: path-filter
        uses: ./.github/actions/pathFiltering
        with:
          package-namespace: ${{ needs.Get-Package-Info.outputs.package-namespace }}

  Build-And-Test:
    needs: Path-Filtering
    if: ${{ github.event_name != 'pull_request' || needs.Path-Filtering.outputs.build-required == 'true' }}
    runs-on: ubuntu-latest
    env:
      DELIVERY_SCRIPTS_PATH: './devops-utility-belt/scripts'
      GIT_BASE_BRANCH: ${{ github.base_ref }}
      GIT_BRANCH: ${{ github.head_ref || github.ref_name }}
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: ☁️ Create GitHub App Token 🔓
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.NCINO_CI_GH_APP_ID }}
          owner: ${{ github.repository_owner }}
          private-key: ${{ secrets.NCINO_CI_GH_APP_SSH_PRIVATE_KEY }}

      - name: 🗃️ Checkout Repo 🗃️
        uses: actions/checkout@v5
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: 🛠️ Force Repository Setup 🛠️
        uses: ncino/action-force-setup@v4
        with:
          ci-github-app-id: ${{ vars.NCINO_CI_GH_APP_ID }}
          ci-github-app-private-key: ${{ secrets.NCINO_CI_GH_APP_SSH_PRIVATE_KEY }}
          ci-ncino-ssh-private-signing-key: ${{ secrets.CI_NCINO_SSH_PRIVATE_SIGNING_KEY }}
          ci-ncino-ssh-public-signing-key: ${{ secrets.CI_NCINO_SSH_PUBLIC_SIGNING_KEY }}
          dev-hub-auth-url: ${{ secrets.DEVOPS_DEV_HUB_AUTH_URL }}
          ncino-cli-install: 'true'
          ncino-cli-version: ${{ vars.NCINO_CLI_VERSION }}
          setup-salesforce-version: ${{ vars.SF_CLI_VERSION }}
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          NPM_TOKEN: ${{ secrets.CI_USER_REPO_ACCESS_TOKEN }}

      - name: 🕵️‍♀️ Validate config XML 🕵️‍♀️
        uses: ncino/action-validate-xml@v1

      # Uncomment if you have Angular or AngularJS jest tests
      # - name: 🧪 Run Angular Tests 🧪
      #   run: npm run test

      # Uncomment once tests have been applied
      # Some repos may need to change this to test:lwc
      # - name: 🧑‍🎤 Run npm test:unit script 👩‍🎤
      #   run: npm run test:unit

      - name: 👩‍🌾 Get OrgFarm Org 👨‍🌾
        id: setup-org
        uses: ncino/action-org-setup/org-provision-action@v5
        with:
          github-token: ${{ secrets.CI_USER_REPO_ACCESS_TOKEN }}
          orgfarm-api-url: ${{ vars.ORGFARM_API_URL }}
          orgfarm-api-key: ${{ secrets.ORG_FARM_API_KEY }}
          preserve-org: ${{ inputs.preserve-org }}
          sftd-api-key: ${{ secrets.SFTD_API_KEY }}
          skip-python-install: 'true'
          clean-org: ${{ steps.determine-org-type.outputs.clean_org }}

      - name: 🚢 Deploy source and encrypt 🚢
        if: ${{ steps.setup-org.outcome == 'success' }}
        uses: ncino/action-org-setup/org-source-push-action@v5

      - name: 🤞 Force Apex Tests 🤞
        if: ${{ steps.setup-org.outcome == 'success' }}
        uses: ncino/action-force-apex-tests@v5
        with:
          auth-url: ${{ steps.setup-org.outputs.auth-url }}
          skip-python-install: 'true'

      - name: 🧹 Post Build Cleanup 🧹
        if: always()
        uses: ncino/action-org-setup/org-cleanup-action@v5
        with:
          orgfarm-api-url: ${{ vars.ORGFARM_API_URL }}
          orgfarm-api-key: ${{ secrets.ORG_FARM_API_KEY }}
          preserve-org: ${{ inputs.preserve-org }}

      - name: 📝 Export Summary 📝
        id: summary
        run: |
          echo "summary<<EOF" >> $GITHUB_OUTPUT
          echo "$(cat $GITHUB_STEP_SUMMARY)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        shell: bash

      - name: 👏 Success Message 👏
        if: ${{ success() }}
        run: cat $DELIVERY_SCRIPTS_PATH/config/deploy_message.txt
        shell: bash
