#* This workflow will run when a dev-branch is merged into release a
#* feature-branch or the release branch. Jobs run in following order:
#*   1. commit-lint: checks commit messages for semantic release.
#*   2. merge-ci: runs the ci build to test feature branch changes on merge.
#*   3. draft-release: creates a draft release in GitHub and transitions tickets to packaging.
#*   4. publish-package: deploys the package to the packaging org and publishes PLM record.
#*   5. update-release: Publishes the github release and transitions tickets to verification.

name: 📚 1GP Publish 📝
on:
 push:
  branches:
   - release
   # - "*.*.x"

env:
 COMMIT_SHA1: ${{ github.sha }}
 GIT_BRANCH: ${{ github.ref_name }}
 REPO_NAME: ${{ github.event.repository.name }}
 RELEASE_FULLNAME: '<< PACKAGE FULLNAME HERE >>'
 NAMESPACE: '<< NAMESPACE HERE >>'
 DELIVERY_SCRIPTS_PATH: './devops-utility-belt/scripts'
 GITHUB_TOKEN: '${{ secrets.CI_USER_REPO_ACCESS_TOKEN }}'

jobs:
 commit-lint:
  name: 📝  Commit Lint
  uses: ncino/<< REPO NAME HERE >>/.github/workflows/commit-lint.yml@release
  secrets: inherit
  permissions:
   contents: read
   pull-requests: read

 merge-ci:
  name: 🔄  Merge CI
  needs: [commit-lint]
  uses: ncino/<< REPO NAME HERE >>/.github/workflows/1gp-ci.yml@release
  secrets: inherit
  permissions:
   id-token: write
   contents: read

 draft-release:
  if: ${{ needs.commit-lint.outputs.release != 'NONE' }}
  name: ⚔︎🐠 Create Pre-release and Transition to Packaging
  needs: [commit-lint, merge-ci]
  runs-on: ubuntu-latest
  outputs:
   id: ${{ fromJson(steps.create-pre-release.outputs.release).id }}
   jira-ticket-ids: ${{ steps.parse-inputs.outputs.jira-ticket-ids }}
   tag: ${{ steps.semantic-release.outputs.tag }}
   url: ${{ steps.semantic-release.outputs.url }}

  steps:
   - name: 🗃️ Checkout Code
     uses: actions/checkout@v4
     with:
      fetch-depth: 0
      token: ${{ secrets.CI_USER_REPO_ACCESS_TOKEN }}

   - name: 🛠️ Force Repository Setup
     uses: ncino/action-force-setup@v3
     with:
      ci-ncino-ssh-private-signing-key: ${{ secrets.CI_NCINO_SSH_PRIVATE_SIGNING_KEY }}
      ci-ncino-ssh-public-signing-key: ${{ secrets.CI_NCINO_SSH_PUBLIC_SIGNING_KEY }}
      dev-hub-auth-url: ${{ secrets.DEVOPS_DEV_HUB_AUTH_URL }}
     env:
      GITHUB_TOKEN: ${{ secrets.CI_USER_REPO_ACCESS_TOKEN }}

   - name: 🦃 Install Node 20 for Semantic Release
     uses: actions/setup-node@v4
     with:
      node-version: 20

   - name: 🚛 Semantic Release
     id: semantic-release
     run: |
      set -e
      npx semantic-release --debug >semantic-release.log
      echo "url=$(cat semantic-release.log | grep -o 'https.*/tag/.*' | tr -d '\n')" >> $GITHUB_OUTPUT
      echo "tag=$(cat semantic-release.log | grep -o '/tag/.*' | tr -d '/tag/')" >> $GITHUB_OUTPUT
     env:
      GIT_AUTHOR_EMAIL: pdedevops@ncino.com
      GIT_AUTHOR_NAME: ci-ncino
      GITHUB_TOKEN: ${{ secrets.CI_USER_REPO_ACCESS_TOKEN }}
      NPM_TOKEN: ${{ secrets.CI_USER_REPO_ACCESS_TOKEN }}

   - name: ✨ Create Pre-release ✨
     id: create-pre-release
     uses: ncino/action-update-release@v2
     with:
      github-token: '${{ secrets.CI_USER_REPO_ACCESS_TOKEN }}'
      tag-name: ${{ steps.semantic-release.outputs.tag }}
      prerelease: true
      draft: false
      body: |
       ## 🔨 Build Information
       * Release generated in job [${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).}

   - name: 📝 Release Summary
     run: |
      echo "## ✏️ Created Pre-release
       * [${{ steps.semantic-release.outputs.tag }}](${{ steps.semantic-release.outputs.url }})
      " >> $GITHUB_STEP_SUMMARY

   - name: 🔬 Run the Jira parsing action
     id: parse-inputs
     uses: ncino/action-jira-issue-parser@v1
     env:
      GITHUB_TOKEN: ${{ secrets.CI_USER_REPO_ACCESS_TOKEN }}
      HEAD_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
      JIRA_USER: ${{ secrets.JIRA_USER }}
      JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
     with:
      pr-title: ${{ env.HEAD_COMMIT_MESSAGE }}

   - name: 🪬 Transition Jira Tickets
     uses: ncino/action-jira-transition@v1
     env:
      JIRA_TRANSITION_WEBHOOK: ${{ secrets.JIRA_TRANSITION_WEBHOOK }}
      PACKAGE_VERSION: ${{ steps.semantic-release.outputs.tag }}
      RELEASE_FULLNAME: << PACKAGE FULLNAME HERE >>
     with:
      issue-ids: ${{ steps.parse-inputs.outputs.jira-ticket-ids }}
      new-status: 'Packaging'

 publish-package:
  name: 🚀 Publish Package to Packaging Org 🚀
  needs: [draft-release]
  runs-on: ubuntu-latest
  steps:
   - uses: actions/create-github-app-token@v1
     id: app-token
     with:
      app-id: ${{ vars.NCINO_CI_GH_APP_ID }}
      private-key: ${{ secrets.NCINO_CI_GH_APP_SSH_PRIVATE_KEY }}

   - name: 🗃️ Checkout Repo 🗃️
     uses: actions/checkout@v4
     with:
      ref: ${{ needs.draft-release.outputs.tag }}
      token: ${{ steps.app-token.outputs.token }}

   - name: 🛠️ Force Repository Setup 🛠️
     uses: ncino/action-force-setup@v3
     with:
      ci-ncino-ssh-private-signing-key: ${{ secrets.CI_NCINO_SSH_PRIVATE_SIGNING_KEY }}
      ci-ncino-ssh-public-signing-key: ${{ secrets.CI_NCINO_SSH_PUBLIC_SIGNING_KEY }}
      dev-hub-auth-url: ${{ secrets.DEVOPS_DEV_HUB_AUTH_URL }}

   - name: 🏷️ Get Commit Sha from Tag 🏷️
     id: get-commit-sha
     run: echo "commit-sha=$(git rev-list -n 1 ${{ needs.draft-release.outputs.tag }})" >> $GITHUB_OUTPUT

   - name: 🗣️ Echo important data 📣
     id: echo-data
     run: |
      echo "🚨 COMMIT_SHA1 = ${{ steps.get-commit-sha.outputs.commit-sha }} 🚨"
      echo "GIT_BRANCH: $GIT_BRANCH"
      echo "PACKAGE_VERSION: ${{ needs.draft-release.outputs.tag}}"
      packageMetadataId=$(jq -r '.plugins.subscriberMetadataPackageId' sfdx-project.json)
      echo "PACKAGE_METADATA_ID: $packageMetadataId"
      echo "package-metadata-id=$packageMetadataId" >> $GITHUB_OUTPUT
      echo "REPO_NAME: $REPO_NAME"

   - name: 📦 Auth to packaging org 📦
     run: |
      echo "${{ secrets.PACKAGING_AUTH_URL }}" >auth.key
      sf auth sfdxurl store --sfdx-url-file auth.key --set-default
      rm auth.key

   - name: 🔐 Enforce platform encryption 🚓
     run: $DELIVERY_SCRIPTS_PATH/enforce_platform_encryption.py
     env:
      CODEBUILD_URL: '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
      DEVOPS_SCRIPTS_PATH: '.'
      PLATFORM_ENCRYPTION_FAILURE_NOTIFICATION_CHANNEL: devops-alerts
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

   - name: 🆙 Update deps in packaging org 🆙
     run: |
      npm i -g @ncino/cli
      username=$(sf org display --json | jq -r '.result.username')
      ncino package install -o $username -w -1
     env:
      SFTD_API_KEY: ${{ secrets.SFTD_API_KEY }}

   - name: 🪄 Convert source to metadata format 🤹‍♂️
     id: convert-source
     run: |
      jq -r '.packageDirectories[] | select(.default=true)' sfdx-project.json >defaultPackage.json
      srcPath=$(jq -r '.path' defaultPackage.json)
      packageName=$(jq -r '.package' defaultPackage.json)
      mkdir dx && mv $srcPath dx/ && rm -rf src/unpackaged defaultPackage.json
      sed -i -e "s/src/dx/" sfdx-project.json
      sf project convert source --root-dir dx/ --output-dir src/ --package-name "$packageName"
      sed -i -e "s/<fullName>/<postInstallClass>PackageInstallHandler<\/postInstallClass><fullName>/" src/package.xml
      package-xml-corrector
      mv config/destructiveChanges*.xml src/
      echo "status=success" >> $GITHUB_OUTPUT

   - name: 🗄️ Upload package.xml artifact 📂
     if: steps.convert-source.outputs.status == 'success'
     uses: actions/upload-artifact@v4
     with:
      name: ncino-package-xml
      path: src/package.xml

   - name: 🚀 Deploy to packaging org 🚀
     run: sf project deploy start --metadata-dir src/ --wait 400 --ignore-warnings

   - name: 🔼 Upload package in packaging org 🔼
     run: |
      pip install pyyaml
      $DELIVERY_SCRIPTS_PATH/sf_package_uploader.py \
        --package-metadata-id ${{ steps.echo-data.outputs.package-metadata-id }} \
        --package-version ${{ needs.draft-release.outputs.tag }} \
        --prefix RELEASE \
        --plm-api-key ${{ secrets.PLM_API_KEY }} \
        --generate-password \
        --add-plm-record
     env:
      PLM_API_BASE_URL: ${{ secrets.PLM_API_ENDPOINT }}

 ###############################################
 ######## 🎊 UPDATE GITHUB RELEASE 🎉 #########
 ###############################################
 update-release:
  name: 🎉 Update Github Release and Transition to Verification
  runs-on: ubuntu-latest
  needs: [publish-package, draft-release]
  steps:
   - name: 🎊 Update Github Release 🎉
     uses: ncino/action-update-release@v2
     with:
      github-token: '${{ secrets.CI_USER_REPO_ACCESS_TOKEN }}'
      tag-name: ${{ needs.draft-release.outputs.tag }}
      prerelease: false

   - name: 📝 Release Summary
     # TODO: Add the PLM Record Link to the release summary
     run: |
      echo "## ✏️ ✅ Published Release 📦
        * [${{ needs.draft-release.outputs.tag }}](${{ needs.draft-release.outputs.url }})
      " >> $GITHUB_STEP_SUMMARY

   - name: 🪬 Transition Jira Tickets
     uses: ncino/action-jira-transition@v1
     env:
      JIRA_TRANSITION_WEBHOOK: '${{ secrets.JIRA_TRANSITION_WEBHOOK }}'
      PACKAGE_VERSION: ${{ needs.draft-release.outputs.tag }}
      RELEASE_FULLNAME: << PACKAGE FULLNAME HERE >>
     with:
      issue-ids: ${{ needs.draft-release.outputs.jira-ticket-ids }}
      new-status: 'Verification'
