name: ✓ Commit Lint
on:
    push:
        branches:
            - feature/*

    pull_request:
        branches:
            - release
            - feature/*

    workflow_call:
        inputs:
            config-path:
                required: false
                type: string
        outputs:
            release:
                description: "Describes the highest level of semantic commit detected"
                value: ${ jobs.lint-commits.outputs.release }

permissions:
    contents: read
    pull-requests: read

jobs:
    lint-commits:
        runs-on: ubuntu-latest
        outputs:
            release: ${ steps.analyze-commits.outputs.release }
        steps:
            - name: Analyze Commits
              uses: ncino/semantic-commit-analyzer@v3
              id: analyze-commits
